### ISSUE TITLE
remove examples relying on did web, so that other resolvers stop failing

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-examples#23]

**Comment by peacekeeper** [comment]
Instead of removing it, it can be an optional example that not all implementations need to support.

**Comment by OR13** [comment]
yes, I feel this is blocked by a better expression of intended to support vs tested

**Comment by OR13** [comment]
I am closing this, its making this fail unnecessarily... we have enough real failures to deal with :)
