### ISSUE TITLE
Issuer and Verifier functionality tests

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/vc-examples#26]
In order to proceed with interop I propose we identify functionality that each VC issuer/ verifier would support described as a test. We can then add those tests to this repo's test suite. The following is a compiled list of tests:

### _Issuer_ 

1. Issuer must return 201 HTTP-Response when a credential is successfully issued.
2. Issuer must support the vc-credential data model with no options field.
3. Issuer must support issuance of credentials with at least 2 different DID methods as an issuer
4. Issuer must return a 400 HTTP-Response when the request is rejected.
5. Issuer must reject if the issuer is not a did or issuer.id is not a did.
6. Issuer must reject if the proofPurpose is not supported in controller
7. Issuer must reject if the verificationMethod does not exist 
8. Issuer must reject if the credential does not contain a context 
9. Issuer must reject a malformed JSON-LD context.

### _Verifier_

1. Verifier must check for a Credential Signature Failure due to mutation of the jws property
2. Verifier must check for a Credential Signature Failure due to lack of create field
3. Verifier must check for a Credential Signature Failure due to invalid proofPurpose 
4. Verifier must reject an added property to the credential
5. Verifier must reject a removed property to the credential
6. Verifier must reject a mutated property to the credential
7. Verifier must reject an added property to the proof object
8. Verifier must reject a removed property to the proof object
9. Verifier must reject a mutated property to the proof object
10. Verifier must be able to verify credentials with atleast 2 different DID methods as the did issuer
11. Verifier must be able to verify presentations when the issuer, holder and subject are different
12.  Verifier must be able to verify presentations when the issuer, holder and subject are the same
13. Verifier response must adhere to proof verification format for credential and presentation
13. Verifier error response must provide an error object
14. Verifier must support the the Ed25519 Cryptographic Suite.
15. Verifier must return a 400 HTTP-Response if the issuer is not a did or issuer.id is not a did.

### Optional Functionality:

1. Issuer may support composition of credentials
2.  Issuer may support issuance of presentations
3.  Verifier may verify a presentation with multiple credentials.
4. Verifier may reject an expired credential 
5. Verifier may reject an expired key 

### Things I am unclear about:
2. Issuer/Verifier may support domain and challenge

**Comment by OR13** [comment]
"Verifier must check for a Bad Issuer" this needs to be clearer...  IMO this is out of scope / business logic... knowing what a "Bad Issuer" is, is a business concern... for PRC they know this... and have no reason to forward such a VC to the verifier endpoint... in the case of Raw Materials, there is no such thing as a"Bad Issuer".... suggest we remove this one.

**Comment by mkhraisha** [comment]
yeah, that makes sense ill edit it.

**Comment by OR13** [comment]
For verification, we should add 2 negative tests for VC and VP... Invalid because of mutation of signature field... and invalid because of key rotation.. the second option will actually be hard to test over HTTP given what we have today, but its worth documenting, and skipping imo.

**Comment by OR13** [comment]
Credential expiration and Key Expiration should also be added to the list, even if we don't all support them.

**Comment by mkhraisha** [comment]
that makes sense, i added them to the optional requirements

**Comment by OR13** [comment]
Invalid Issuance Rquest Test Cases:
- issuer is not a did or issuer.id is not a did.
- proofPurpose is not supported in controller
- verificationMethod does not exist
- credential does not contain a context (same as malformed)

**Comment by mkhraisha** [comment]
> * verificationMethod does not exist

**Comment by OR13** [comment]
removing "Issuer must support the the Ed25519 Cryptographic Suite." ... this is covered by verificationMethod Tests... and we have agreed to only use this suite.... so this test is not super helpful.

**Comment by mkhraisha** [comment]
fair enough feel free to remove the same comment on the verifier

**Comment by OR13** [comment]
I question if we should keep "Verifier must return a 400 HTTP-Response if the issuer is not a did or issuer.id is not a did."

... because URIs for controllers might be desirable... and they are VC Data Model compliant... I suggest we remove this.

**Comment by OR13** [comment]
granted I suggested it initially, i think what we really want is a negative and positive test for URI and DIDs for each case.

**Comment by OR13** [comment]
I created seperate test suite for this ticket, here are the results: https://w3c-ccg.github.io/vc-examples/plugfest-2020.html

**Comment by OR13** [comment]
Need to add "Issuer API returns 400 when issuer does not match "assertionMethod / verificationMethod" in options."

**Comment by OR13** [comment]
can someone convert this list to a markdown document and commit it to the repo so we can iterate on it outside of an issue?

**Comment by OR13** [comment]
Lets close this issue, and open any new issues, discuss the topic and open a PR against the markdown when we feel appropriate.
