### ISSUE TITLE
Crude Product VC example - ID field is not a URI

### ISSUE THREAD

**Issue by rolsonquadras** [w3c-ccg/vc-examples#27]
The [Crude Product VC](https://github.com/w3c-ccg/vc-examples/blob/master/docs/crude/examples/v1.0/crude-product-verifiable-credential-v1.0.json#L7) example has UUID as the value for `id` field. As per the [VC model](https://www.w3.org/TR/vc-data-model/#identifiers) spec, the id field MUST be a URI.

**Comment by vaishnavipanchal23** [comment]
Noted! I will fix that!

**Comment by OR13** [comment]
@vaishnavipanchal23  did this get fixed?

**Comment by vaishnavipanchal23** [comment]
@OR13 Yes!

**Comment by vaishnavipanchal23** [comment]
I did refer to this issue in my PR, apparently merging the PR did not close it.
