### ISSUE TITLE
Is unique credential id a requirment

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-examples#58]
should everyone be using this?
```
if(issuer.endpoint.includes('digitalbazaar.com')) {
                  vendor.credentials = annotateWithUniqueId(vendor.credentials);
                }
```

**Comment by gannan08** [comment]
@OR13 Yes, I believe everyone should be using it. Credentials are intended to have unambiguous identifiers, so every time a test is run we should give them unique IDs.

**Comment by OR13** [comment]
We should remove the vendor check and apply this to everything at the top of the describe block.

**Comment by gannan08** [comment]
Closing per https://github.com/w3c-ccg/vc-examples/commit/963654aa132abab8ad156c27aaefd76aeb1c9680
