### ISSUE TITLE
Issuer test case 5 is probably not a good idea.

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-examples#59]
5. The Issuer's Issue Credential HTTP API MUST reject if the value of `"credential.issuer"` or `"credential.issuer.id"` in the body of the POST request is not a DID.

VC Data Model does not require this, I suggest we eliminate this test case.

**Comment by gannan08** [comment]
Yes, noticed this as well. If we change `DID` to `URI`, then we can preserve the test. We could also remove the test entirely. Either option is okay with me.

**Comment by msporny** [comment]
Change it to URI... it definitely shouldn't be "DID".

**Comment by OR13** [comment]
this has been changed here: https://github.com/w3c-ccg/vc-examples/pull/60

**Comment by OR13** [comment]
resolved
