### ISSUE TITLE
no challenge option to verifier behavior

### ISSUE THREAD

**Issue by troyronda** [w3c-ccg/vc-examples#62]
If the challenge option is not passed but the proof contains a challenge, it seems the test suite currently expects the verifier to fail the request.

Is this the desired behavior?

**Comment by OR13** [comment]
I assume you are referring to the verify presentation endpoint... 

Here is the expected behavior in my mind:

1. if the VP contains a proof, but the options provided don't match FAIL.
2. if the VP does not contain a proof but options are provided FAIL.
3 if  the VP does not contain a proof and no options are provided, just check the VCs.

**Comment by OR13** [comment]
If their is agreement, then the test readme should be updated first. we should only make the tests reflect what is in the readme... if its not clear enough, we need to fix the language first.

**Comment by gannan08** [comment]
> 1. if the VP contains a proof, but the options provided don't match FAIL.

Correct, if you are validating an authentication proof on a Verifiable Presentation. One MUST provide the necessary options for verifying that presentation: challenge, domain, etc.

> 2. if the VP does not contain a proof but options are provided FAIL.

If we qualify the last part to say "proof options", then I'm in agreement. There may be other options provided in the future that don't involve proofs.

> 3. if  the VP does not contain a proof and no options are provided, just check the VCs.

That sounds fine.

**Comment by OR13** [comment]
updated "options' => "proof options". agree.

**Comment by OR13** [comment]
I think this might be ready for a PR, these cases should be added to the readme first.

**Comment by peacekeeper** [comment]
The [Verifier API](https://github.com/w3c-ccg/vc-verifier-http-api/blob/svip-interop/api.yml) we agreed to use for the plugfest doesn't allow a "challenge" option.

I can understand how that option makes sense, but I'm not happy with the fact that last-minute tests are being written against some undocumented version of the API that is different from the one we agreed on...

I therefore think those tests should be removed from the plugfest test suite (and then added back in later).

**Comment by peacekeeper** [comment]
(Or alternatively, the test suite should indicate which version of the Verifier API it is testing - with a link to an updated Swagger definition)...

**Comment by OR13** [comment]
the only version of the verifier api that it can test against doesn't define challenge, and domain, and can therefore cannot verify presentations, despite having endpoints ostensibly defined to support this.... I agree with @peacekeeper, those tests should be skipped for everybody....

**Comment by troyronda** [comment]
We are updating our verifier behavior in line with https://github.com/w3c-ccg/vc-examples/issues/62#issuecomment-619228361

**Comment by dlongley** [comment]
@peacekeeper,

> I can understand how that option makes sense, but I'm not happy with the fact that last-minute tests are being written against some undocumented version of the API that is different from the one we agreed on...

This isn't last minute; it was discussed on several calls and we have had agreement for a long while that some parties would be testing verifying presentations and others would not. That's just fine; test whatever you can or want to. We know that different parties will skip certain tests that they do not implement. There are a number of parties that have agreed to implement verifying presentations and only those parties will run those tests related to doing so. What we don't want to see is only one party implementing a given test -- such a test does not demonstrate interop.

**Comment by peacekeeper** [comment]
@dlongley the point is not whether challenge/domain are a good thing (they are!).

The point is that the tests currently seem to test some undocumented variation of the VC Verifier HTTP API, i.e. not [the one in the CCG repo](https://github.com/w3c-ccg/vc-verifier-http-api/blob/d4f5a4104f5626bb18c9dac83c732648c353d01e/api.yml).

**Comment by dlongley** [comment]
@peacekeeper, yes, that's understood. And that's what we agreed to do. The tests will be authoritative for those parts. We'll need to update the API specs after the interop plugfest based on what was tested and where we want to go.

**Comment by OR13** [comment]
I believe this is resolved, and we will address it again when we get the api specs merged. I will close soon without objection.

**Comment by OR13** [comment]
Please move any further discussion here if needed https://github.com/w3c-ccg/vc-http-api
