### ISSUE TITLE
plugfest test for added property - Proof vs JSON-LD testing

### ISSUE THREAD

**Issue by troyronda** [w3c-ccg/vc-examples#63]
For the “The Verifier’s Verify Credential HTTP API MUST fail to verify a Verifiable Credential with an added property to the credential.“ (similarly with proof case).

Is the intention to check for properties that are not in the JSON-LD context OR check that an additional property hasn’t been added (that isn’t included in the signature)? Note the property that is added is “newProp”: “bar” … which isn’t in the JSON-LD context.

The tests should be delineated so we separate testing of proofs (and extra properties not in the proof) from testing of JSON-LD.

**Comment by peacekeeper** [comment]
I agree with @troyronda , the tests should probably add a property that is in the JSON-LD context, so that we test specifically the proof checking part, rather than checking JSON-LD errors.

**Comment by dlongley** [comment]
If it's easier for current testing to just support adding a property that is defined but not signed, I can support that. However, longer term, I think the VC HTTP API should fail to verify a VC that has any properties that aren't defined. It should be possible for applications to avoid doing their own processing to determine if a property is not defined (and therefore not signed). I think that's the more secure/simpler approach for applications (places the extra burden on verifiers).

**Comment by OR13** [comment]
I'm hearing the following proposal:

1. Issuer should fail to issue a credential which has properties not defined in its context.
2. Verifier should fail to verify a credential which has properties added (after issuance) that are in its context. 
3. Verifier should fail to verify a credential which has properties added (after issuance) that are not in its context.

**Comment by peacekeeper** [comment]
Agree with @OR13 .. For the plugfest test suite the item 2. is probably the most interesting, since it focuses specifically on the proof checking rather than JSON-LD errors. The other items 1. and 3. are "nice to have".

**Comment by OR13** [comment]
Please move any further discussion here if needed https://github.com/w3c-ccg/vc-http-api
