### ISSUE TITLE
Relationship between issuer and verificationMethod

### ISSUE THREAD

**Issue by troyronda** [w3c-ccg/vc-examples#67]
I am curious about verifying the relationship between the `issuer` and the `verificationMethod`. And similarly between `holder` and the `verificationMethod`.

**Comment by dlongley** [comment]
See the NOTE here for more information: https://www.w3.org/TR/vc-data-model/#proofs-signatures-0

**Comment by troyronda** [comment]
This might be a candidate for a future test scenario.

**Comment by OR13** [comment]
@troyronda is this actionable? If there is discussion to be had, lets make that clear, other wise lets close. I'm not sure how to address this issue.
