### ISSUE TITLE
Digitial Bazaar Issuer does not support CORS

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-examples#71]
Mavennet and Transmute demo sites cannot use it.

https://issuer.interop.transmute.world/
https://mavennet.github.io/issuer-verifier-frontend/

**Comment by gannan08** [comment]
@OR13 Sites were updated last night with fixes. Please let me know if this issue still persists.

**Comment by OR13** [comment]
@gannan08 confirmed to to be working now.
